### ISSUE TITLE
Type Error in Professor OAK's Lab

### ISSUE THREAD

**Issue by clar0867** [Pokemon-PythonRed/Pokemon-PythonRed#71]
Receiving a type error when attempting to talk to Professor OAK in the lab after initially receiving first Pokemon.

Current Location: OAK's Lab

[a] - Go to Pallet Town
[1] - Lab Assistant (Left)
[2] - Lab Assistant (Right)
[3] - Professor OAK
[4] - OAK's Computer

> 3

OAK: You've caught a total of...
Traceback (most recent call last):
  File "/home/kali/Desktop/Pokemon-PythonRed-master/app/./main.py", line 803, in <module>
    sg(f'\n{sum(1 if i["caught"] else 0 for i in save["dex"])} Pokémon!')
  File "/home/kali/Desktop/Pokemon-PythonRed-master/app/./main.py", line 803, in <genexpr>
    sg(f'\n{sum(1 if i["caught"] else 0 for i in save["dex"])} Pokémon!')
TypeError: string indices must be integers

**Comment by nasserkessas** [comment]
I've raised a [PR](https://github.com/Pokemon-PythonRed/Pokemon-PythonRed/pull/75) to fix this issue, hopefully it will get approved and merged.

**Comment by TurnipGuy30** [comment]
Thank you for your contribution!
